name: cardinal
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.2.beta


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.4
  dotted_border: ^2.0.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.2.2
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/bottom_navigation/
